### ISSUE TITLE
template has StagesAvailable

### ISSUE THREAD

**Issue by RegEM** [scrthq/VaporShell#18]
Hi Nate, Congrats on getting v2 out. I'm sure it will be a great success.

I tried importing a cloud formation template. Loaded ok. But when I try to export to yaml, vaporshell objects. There is a 'stagesAvailable' header on the template. I'm sure you can guess the error. 

I worked around this by removing the StagesAvailable element and the TemplateBody wrapper. Then I exported successfully.  I then loaded the exported template into the AWS template designer. So with out further testing, looks excellent so far. 

Not that it is a super complicated template, but it did take me a long time to create with Serverless. I'm thrilled vaporshell imported it without much issue. Planning to move everything to Vaporshell now.

Here's the problem elements:
`{
    "StagesAvailable": [
        "Original", 
        "Processed"
    ], 
    "TemplateBody": {
        "AWSTemplateFormatVersion": "2010-09-09", 
        "Outputs": {
rest of template...`

The error:
`Exception calling "ToYAML" with "1" argument(s): "Unable to find any resources on this Vaporshell template. Resources are required in CloudFormation templates at the minimum."`

In my template I have the two elements, "StagesAvailable", and "TemplateBody".
The "TemplateBody", has four elements, "AWSTemplateFormatVersion", "Outputs", "Description", and "Resources".

I did run into some other kind of file type issue too. To fix, I had to copy the text from my template file to a demo export file. I'm not sure what is causing this, but I went back and confirmed that the error reported above exists in either file. So I'm sure it is just the way the original import template file was created. I think it was via downloading it from cfn via awscli. Some kind of windows UTF issue I presume, and unrelated to the 'stagesAvailable' issue reported here.

Anyways. No big concern re: either issue. Just thought I would let you know about the headers preventing the export.

Regards, Richard

**Comment by scrthq** [comment]
Thanks, Richard!!

Did you pull that template directly from CloudFormation in the AWS console? It looks like you pulled a Change Set JSON, which would make sense as you have to go through a Change Set to deploy a SAM template.

For those, you have 2 stages: Original (what the template looked like with Transforms still in it when originally uploaded to CloudFormation) and Processed (what the template looks like after CloudFormation goes through it's Transforms and results in the final template layout)


Curious on where you pulled the template from that you imported, for sure!

**Comment by scrthq** [comment]
Ahh, seeing now that you pulled it from the aws cli, assuming with the `get-template` command: http://docs.aws.amazon.com/cli/latest/reference/cloudformation/get-template.html

```
Output
TemplateBody -> (string)

Structure containing the template body. (For more information, go to Template Anatomy in the AWS CloudFormation User Guide.)
AWS CloudFormation returns the same template that was used when the stack was created.
StagesAvailable -> (list)

The stage of the template that you can retrieve. For stacks, the Original and Processed templates are always available. For change sets, the Original template is always available. After AWS CloudFormation finishes creating the change set, the Processed template becomes available.
(string)
```

That being said, if you have the StackName / StackID, you can do that directly with 2.0 😄 :

```powershell
Import-VaporShell -TemplateBody (Get-VSStack -Template -StackId $stackName).TemplateBody
```

**Comment by RegEM** [comment]
I don't recall. I didn't see a spot on cfn to download my template, so I assumed I must have used awscli. I checked the designer too, and I don't see a way I could get the template that way.

In hindsight it may have been via a powershell module. 

But sounds like you've got it figured that it was awscli. That's what I figured.

Trying the direct import now.

**Comment by RegEM** [comment]
I get this error:
`ProcessRequest4 : Multiple ambiguous overloads found for "AmazonCloudFormationClient" and the argument count: "2".`
Maybe cause I'm version4?

**Comment by RegEM** [comment]
Even this fails for me 'Get-VSStack -List', same error. 
Too bad...

**Comment by scrthq** [comment]
Spinning up my Win7 x PS4 VM now! I didn't hit that when I was testing, but I have an idea

On your credentials file, do you have a region specified under the profile you're using?

`Get-Content ~\.aws\credentials` should show you quick, here's a redacted look at mine:

```
[default]
aws_access_key_id={redacted}
aws_secret_access_key={redacted}
region=us-west-1
[scrthq]
aws_access_key_id={redacted}
aws_secret_access_key={redacted}
region=us-west-2
```

**Comment by scrthq** [comment]
![image](https://user-images.githubusercontent.com/12724445/30517196-5e88be4a-9b1d-11e7-9acb-e40884128792.png)

Here's my PSV4 test

What's the latest version of .NET that you have installed on that machine?

**Comment by RegEM** [comment]
how do i get net version? no region in my credentials..

**Comment by scrthq** [comment]
Ah ha! Pulled the region off and replicated it, definitely the region:)

![image](https://user-images.githubusercontent.com/12724445/30517214-f584d39c-9b1d-11e7-9003-d1136cabab42.png)


Can you run `Set-VSCredential -Region USWest1` then retry your stack list? Should work after setting the region

**Comment by scrthq** [comment]
(or set it to whatever region you'd like to use)

**Comment by RegEM** [comment]
bear with me.. should work, but doesn't like my current iam user

**Comment by scrthq** [comment]
come onnnnnn (kidding)... no worries! looking forward

**Comment by RegEM** [comment]
I forget how to set my profile... lol

**Comment by scrthq** [comment]
lol... 

```powershell
Set-VSCredential -AccessKey $accessKey -SecretKey $secretKey -Region USWest1 -ProfileName DevAccount
```

**Comment by scrthq** [comment]
adjust accordingly and all that

**Comment by RegEM** [comment]
durnn it all, two different secret keys and all that lead to the same iam user, that doesn't have permission,,, aaargh!

**Comment by scrthq** [comment]
![foreverflip](https://user-images.githubusercontent.com/12724445/30517312-d6943f92-9b20-11e7-9931-78b3121c513e.gif)

**Comment by scrthq** [comment]
in case it's easier, I have Gitter setup for more chat style back and forth around VaporShell: 

https://gitter.im/VaporShell/Lobby

https://gitter.im/VaporShell/Help

**Comment by RegEM** [comment]
never tried it.. maybe some time. I think the set-vscred is not playing nice, and I'm stuck on the same profile. I'll get back when resolved

**Comment by scrthq** [comment]
2.0.1 coming to PS Gallery now that adds better context to the error you had. It also checks the imported template for a TemplateBody property and dives into that layer (so your original issue would work regardless if you pulled the body out or not)

Let me know if you get any errors with Set-VSCredential still!

**Comment by scrthq** [comment]
![image](https://user-images.githubusercontent.com/12724445/30517422-3d294132-9b24-11e7-87f5-44f10cb0a1d8.png)

So you'll see that vs the ambiguous error you saw prior

**Comment by scrthq** [comment]
https://www.powershellgallery.com/packages/Vaporshell/2.0.1 upped!

**Comment by RegEM** [comment]
Cool. You're fast..lol
 I ended up nowhere with Set-VSCredential, but changed the permission on the iam user to allow the formation listing (works). Have to run away for awhile, but will try the direct import later today.

**Comment by scrthq** [comment]
No worries! Let me know once you're covered and I'll close this out! Cheers!

**Comment by RegEM** [comment]
how can i list the profile that get-vs uses? I set it as you showed, but it doesn't seem to be correct. as the iam user listed doesn't match the keys i use on the commandline. anyways will be gone for awhile.

**Comment by scrthq** [comment]
The functions will use whichever of these has a value first, in order of precedence:

1. The profile name you pass to the `-ProfileName` parameter on the function itself:
- `Get-VSStack -List -ProfileName devAccount`
2. The value for `$env:AWS_PROFILE`, if set
3. "default", if 1 and 2 are not matched

**Comment by RegEM** [comment]
Thanks. Yeah just stuck in default profile, though I had thought I was setting it with the proper keys, as my cred file was changing. I have a default 'NetSDKCredentialsFile' too, but I don't think it's a factor.

Anyways ran this with success. Doubt I'll go back to the original issue considering I can retrieve direct from cfn. thanks, close her out.. you are awsome sir!

`PS> Import-VaporShell -TemplateBody (Get-VSStack -Template -StackId 'thestack' -ProfileName devAccount ).TemplateBody
AWSTemplateFormatVersion      Description                   Resources                     Outputs
------------------------      -----------                   ---------                     -------
2010-09-09                    The AWS CloudFormation tem... @{ServerlessDeploymentBuck... @{ServerlessDeploymentBuck...`

**Comment by scrthq** [comment]
Awesome!!

So, the NetSDKCredentialsFile is what AWS Tools for PowerShell uses. I opted to leverage the shared credentials file instead, as the NetSDKCredentialsFile is a little weird with .netstandard / Linux / macOS. Nothing wrong with it, but VaporShell is not looking there at all

**Comment by RegEM** [comment]
cool. i eliminated the iam permission i set earlier and confirmed it was for the default in my cred file, So i figured the net file was not used. still not sure why I was stuck., but not uncommon..lol. Bye for now.

**Comment by scrthq** [comment]
No worries! Cheers man!
