### ISSUE TITLE
More DSL-like style

### ISSUE THREAD

**Issue by ebekker** [scrthq/VaporShell#31]
Ever think about using a more DSL-like style to define your templates, something like [this](https://github.com/ezshield/posh-awscfn/wiki/Cmdlet-Conventions)?

**Comment by RegEM** [comment]
That looks interesting. Thanks for posting.
Ran across this while looking up DSL. https://kevinmarquette.github.io/2017-02-26-Powershell-DSL-intro-to-domain-specific-languages-part-1/
Cheers.

**Comment by ebekker** [comment]
Good find, thanks for the link!

**Comment by scrthq** [comment]
@ebekker totally have! Issue #12 was actually to track just that and it stemmed from a discussion on Reddit with Kevin Marquette actually @RegEM . His blog post is fantastic for that. That being said, it's something I've wanted to do but haven't felt a big need to do it personally. If there's a big need or want for it, I'm all ears to prioritize it more! Interested in your guys' feedback on it!

**Comment by ebekker** [comment]
Just saw your [comment](https://github.com/scrthq/VaporShell/issues/12#issuecomment-330011386) about a DSL losing some of the PS auto-complete *goodness*.  I think in AwsCfn struck a good balance, where it was natural enough to map to the CFN templating language, but preserving support for IntelliSense in ISE was actually a primary goal throughout.

Agree, @KevinMarquette 's 5-part piece was great, it really summarized in a very clear and concise fashion the different DSL techniques available in PS at present.

I stopped working on AwsCfn a while back when we started to transition away from CFN, but now that we've adopted Terraform as our primary infra description tool we've had some time to really work with it, I've actually been thinking that there may be some benefit to applying a similar approach (a PS DSL over TF) to address some of the shortcomings in TF's static description format.  Kevin's articles gave me a few good ideas I'll have to explore if we go that route...

**Comment by scrthq** [comment]
@ebekker nice! So you were involved with AwsCfn then? Awesome! I checked out the docs, it's a pretty great approach to using a PS DSL for CFN template building! My thought process on approach was slightly different, I'll have to keep it in mind to play around with! DSL's in PS are interesting in how they differ from "expected" PowerShell syntax as well as what's going on behind the scenes.

**Comment by ebekker** [comment]
Yes, I agree -- I really don't like to use the term DSL as much as DSV (Domain-specific Vocabulary) when it comes to PS because you really have to compromise between what would be ideal in a true DSL format vs what is possible in PS and also what still benefits from the PS ecosystem -- for example, maintaining support for intellisense.

That's why I'm really hopeful that some day [RFC0017](https://github.com/PowerShell/PowerShell-RFC/blob/master/3-Experimental/RFC0017-Domain-Specific-Language-Specifications.md) will actually get finalized and implemented to add true language-extensibility support to PS.

Otherwise, some of the tricks, like supporting a [pseudo-hashtable syntax](https://kevinmarquette.github.io/2017-03-13-Powershell-DSL-design-patterns/#hashtable-builder), lose a lot of their effectiveness because you can't get any contextual help from the tooling.

**Comment by scrthq** [comment]
Totally agree as well. One of the things I personally appreciate most about VaporShell is the coverage of CFN resources and resource properties in functions, allowing every one of them to take advantage of Intellisense/tab-completion/etc that PowerShell offers. Building out a DSL that offers the same functional benefits is hard to imagine (at least for me).

Here's what I'm somewhat envisioning, using the [SAM template example from my README on this repo](https://github.com/scrthq/VaporShell#examples):

```powershell
Template "A function triggered on a timer." {
    Resource SAMFunction "ScheduledFunction" {
        Handler = "index.handler"
        Runtime = "nodejs6.10"
        CodeUri = ".\code"
        Events {
            SAMScheduleEventSource "Timer" {
                Schedule = "rate(5 minutes)"
            }
        }
    }
}
```

Another example with a standard, non-SAM template:

```powershell
Template "Server 2016 EC2 stack" {
    Mapping "AMI" @{
        "us-east-1" = @{
            id = "ami-08910872"
        }
        "us-west-2" = @{
            id = "ami-f6d8008e"
        }
    }
    Resource EC2Instance "Svr2016" {
        ImageId = FnFindInMap {
            MapName = "AMI"
            TopLevelKey = (FnRef $_AWSRegion)
            SecondLevelKey = "id"
        }
        KeyName = "WindowsKey"
    }
}
```

**Comment by ebekker** [comment]
Now, in your examples, are those *hand-crafted* cmdlets under the hood?

The approach I took with AwsCfn was to auto-generate all the resources from the AWS-maintained CFN schema.  I was under the impression that you were doing the same thing?  So all the nested properties were derived from the schema and their descriptions.

So in the example above if it's not coming from the schema, then it's something you have to build manually and that could be very cumbersome and quite a task to cover the full spectrum.

**Comment by scrthq** [comment]
@ebekker - My approach for the DSL style would be more to add it as an additional option in this module vs creating a seperate, DSL only module. That being said, I would want to be able to reference the existing, auto-generated resource/property functions with short names. DSL specific functions would be static and cover the unique ones like `Template` and `Resource` so duplicate auto-generated functions wouldn't need to be generated just for the DSL side (it would more or less act as a wrapper for the full module itself).

**Comment by scrthq** [comment]
@ebekker DSL wrapper built out, deploying soon

**Comment by scrthq** [comment]
Feel free to check it out if you're curious: https://github.com/scrthq/VaporShell/blob/feature/dsl_v1/VaporShell/DSL/VaporShell.DSL.psm1

Example showing a couple of the functions adding a mapping, resource and custom resource (not a real useful example outside of demonstrating syntax):

```powershell
Template -Desc "Server 2016 EC2 stack" {
    Mapping "AMI" @{
        "us-east-1" = @{
            id = "ami-08910872"
        }
        "us-west-2" = @{
            id = "ami-f6d8008e"
        }
    }
    Resource EC2Instance "Svr2016" {
        ImageId = FnFindInMap "AMI" (FnRef $_AWSRegion) "id"
        KeyName = "WindowsKey"
    }
    CustomResource "Custom::SeleniumTester" "MySelineumTest" {
        Properties = @{
            serviceToken = "arn:aws:sns:us-west-2:123456789012:CRTest"
            seleniumTester = "SeleniumTest()"
            endpoints = @("http://mysite.com", "http://myecommercesite.com/", "http://search.mysite.com")
            frequencyOfTestsPerHour = @("3", "2", "4")
        }
    }
}
```

**Comment by scrthq** [comment]
![image](https://user-images.githubusercontent.com/12724445/39404599-a0eefa26-4b5b-11e8-9adb-883e75a4223e.png)

**Comment by ebekker** [comment]
Very cool!

**Comment by scrthq** [comment]
I have possibly one more tweak to add, but this is deployed as of the latest version of VaporShell if you want to mess around. No worries if not, I know you have your own module and are also Terraform'ing it up anyway, but I'm curious on your feedback if you do play with it!

Thanks for sparking my motivation to revisit the DSL idea, cheers!
