### ISSUE TITLE
Lambda Function updating? 

### ISSUE THREAD

**Issue by RegEM** [scrthq/VaporShell#32]
Hi Nate, My goal is to re-bundle my lambda code into a local directory pointed to by the codeuri in New-SAMFunction. And then redeploy the new code(over and over again) to lambda, triggering an update. Is this currently possible?

If not maybe you have a suggestion? Maybe I can remove the lambda resource, and then do a change set, then put it back in again?

I can tell the code is uploaded to s3 ok. But the change set fails.
```WARNING: Change Set FAILED! Reason: No updates are to be performed.```
This is with vaporize. 

Incidentally, when I run deploy, I get the following error.
```WARNING: Change Set FAILED! Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless
Application Specification document. Number of errors found: 1. Resource with id [myfunction] is invalid.
'CodeUri' is not a valid S3 Uri of the form "s3://bucket/key" with optional versionId query parameter.```

**Comment by RegEM** [comment]
I forgot I can just do this. Once I fixed my handler issue from before, this works fine. 

```node .\bundlemyfunction.js
aws lambda update-function-code --function-name 'myfunction' --zip-file fileb://./z
ipfiles/myfunction.zip```

Or with Powershell doing it like this:

```Write-S3Object -BucketName mydeployment -File myfunction.zip
Update-LMFunctionCode -FunctionName myfunction -BucketName mydeployment -Key myfunction.zip```

**Comment by scrthq** [comment]
@RegEM - is the CloudFormation template different, i.e. the bucket location or key? I could be wrong, but if all you're doing is updating your Lambda code at the same bucket/key (i.e. versioning your code), I don't think you'd need to push a new CloudFormation template; you'd just update your code in S3 as you are doing in your response. In other words, the CloudFormation template build the Lambda function for you with pointers to the code, so if your code location remains the same, there's nothing to update from the CloudFormation side. I haven't personally dealt with Lambda too much, so again, I could be off here, but that's my expectation based on what the CloudFormation template includes and what you are primarily looking to update. A different experience would happen if you're using the ZipFile parameter with inline code vs the S3Bucket and S3Key parameters, as the code would then be embedded in the CloudFormation template itself and differences would more than likely trigger an update with the new Change Set.

`vsl deploy` won't work if your template is referencing a local path (that's what `vsl package` and inherently `vsl vaporize` would do for you, spitting out a new template with the S3 URI's in place of the local code path and deploying the updated template).

**Comment by RegEM** [comment]
You're right. My expectations didn't match the reality. I much appreciate your explanation.

Maybe you could differentiate the S3Bucket/S3Key or zipfile type in the deploy, and then when found update via Update-LMFunctionCode?

I think you are uploading via New-VSS3Object. Not sure if it is done even when there is no change to the code. Not that I am currently using versions, but there may be some issues there.

To be clear (trying), I'm ok with just running the cli commands after changes to my lambda code. It's just occasionally I may try to do a change set for some other resource, permissions etc.. It would be nice if the same method I used initially, updated a change too. 

Cheers. Thanks for your efforts.
