### ISSUE TITLE
ERROR: Parameter only accepts the following types

### ISSUE THREAD

**Issue by webmin88** [scrthq/VaporShell#35]
I'll use New-VSEC2Route as the example but I suspect the issue pervades into other Cmdlets. In parameters like -GatewayId, -NatGatewayId, etc Adding a conditional value to those parameters are rejected because they are not type System.String or VaporShell.Function. Examples below:

$subnetRoute = New-VSEC2Route -LogicalId PublicRouteAZ3 -DestinationCidrBlock 0.0.0.0/0 -GatewayId ((Add-ConIf -ConditionName GatewayTypeIsGateway -ValueIfTrue (Add-FnRef -Ref PublicRouteEndpointId) -ValueIfFalse (Add-FnRef -Ref "$_AWSNoValue"))) -RouteTableId (Add-FnRef -Ref SubnetAZ3RouteTable)

command results in:

New-VSEC2Route : This parameter only accepts the following types: System.String, Vaporshell.Function. The current types of the value are:
Vaporshell.Condition.If, Vaporshell.Condition, System.Management.Automation.PSCustomObject, System.Object.

I'd like to see the parameter accept conditional values so the resulting CloudFormation can look like:

"PublicRouteAZ3": {
  "Properties": {  
    "DestinationCidrBlock": "0.0.0.0/0",
    "RouteTableId": {"Fn::Ref": "SubnetAZ3RouteTable"},
    "GatewayId": {
      "Fn::If": [
        "GatewayTypeIsGateway",
        {"Fn:Ref": "PublicRouteEndpointId"},
        {"Fn::Ref": "AWS::NoValue"}
      ]
    }
  }
}

Please let me know if I can provide any additional details.

**Comment by scrthq** [comment]
@webmin88 thanks for opening this up and including replication details! 100% makes sense and should be an easy fix, I'll try and get an updated version out by tonight!

Thanks, Brandon!!

**Comment by scrthq** [comment]
![image](https://user-images.githubusercontent.com/12724445/44749192-73113c00-aad7-11e8-8f15-b8c002c1c9ce.png)

[v2.4.1 with fix out now on PS Gallery](https://www.powershellgallery.com/packages/Vaporshell/2.4.1)! Confirmed fixed per above screenshot. Update when you can then let me know if all is gravy for you!

**Comment by webmin88** [comment]
I know it's been a few days, but I just wanted to let you know your fix worked and this issue can be closed. Thanks for the quick response.

**Comment by scrthq** [comment]
@webmin88 no worries!! Glad you're sorted!

**Comment by scrthq** [comment]
Thanks for confirming!!
