### ISSUE TITLE
Application Load Balancer Redirect Config

### ISSUE THREAD

**Issue by NikitaGor** [scrthq/VaporShell#45]
Hi Nate,

I've been trying to spin up a target group with basic redirect from port 80 to 443 however seems like the required functionality is missing.
When you specify a default action of type redirect AWS requires you to specify what's called a redirect config.

Function:
$albListenerRedirectdAction = Add-VSElasticLoadBalancingV2ListenerAction -TargetGroupArn (Add-FnRef "AlbTargetGroup") -Type "redirect"

Documentation:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-defaultactions.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-redirectconfig.html

Can you please have a look at that one? Thank you.

**Comment by scrthq** [comment]
Hey @NikitaGor - I believe you're looking for the `RedirectConfig` parameter on `Add-VSElasticLoadBalancingV2ListenerAction`. You'll need to use `Add-VSElasticLoadBalancingV2ListenerRedirectConfig` to create the config.

```powershell
$albListenerRedirectdAction = Add-VSElasticLoadBalancingV2ListenerAction -TargetGroupArn (Add-FnRef "AlbTargetGroup") -Type "redirect" -RedirectConfig (Add-VSElasticLoadBalancingV2ListenerRedirectConfig -Host $rcHost -Path $rcPath -Port $rcPort -Protocol .......)
```

for clarity:

```powershell
$configSplat = @{
    Host = $rcHost
    Path = $rcPath
    Port = $rcPort
}
$actionSplat = @{
    RedirectConfig = (Add-VSElasticLoadBalancingV2ListenerRedirectConfig @configSplat)
    TargetGroupArn = (Add-FnRef "AlbTargetGroup")
    Type = "redirect"
}
$albListenerRedirectdAction = Add-VSElasticLoadBalancingV2ListenerAction @actionSplat
```

**Comment by NikitaGor** [comment]
Sorry Nate, pebkac!
All good from my end.
Thanks!

**Comment by scrthq** [comment]
No worries! Rubber ducking is needed sometimes and easy fixes are a welcome occasion 😄 

Thanks for using VaporShell! I have some cool additions coming soon =]
