### ISSUE TITLE
Module Name Needs Fix in PowerShell Gallery

### ISSUE THREAD

**Issue by ScriptAutomate** [scrthq/VaporShell#59]
### Client

- OS: Ubuntu 18.04
- PSCoreVersion: 6.2.2

### Issue

```powershell
PS> Find-Module VaporShell | select Version, Name, Repository

Version Name       Repository
------- ----       ----------
2.8.0   Vaporshell PSGallery

```
*Vaporshell* should be named *Vapor**S**hell*, otherwise the case will break the module path and the module cannot be imported.

`Install-Module` from the PowerShell Gallery results in:
```
# Expected Path for VaporShell
/home/$ENV:USER/.local/share/powershell/Modules/VaporShell
# Actual Path is for Vaporshell
/home/$ENV:USER/.local/share/powershell/Modules/Vaporshell
```
Case sensitivity prevents the module from being imported because the module dir string name differs from the module `.psm1` file string name (`/Vaporshell/` vs. `VaporShell.psm1`).

#### Temp Fix

```bash
# Rename Vaporshell dir to VaporShell
mv /home/$ENV:USER/.local/share/powershell/Modules/Vaporshell /home/$ENV:USER/.local/share/powershell/Modules/VaporShell
```

**Comment by scrthq** [comment]
thanks for opening this up, @ScriptAutomate ! Very fair point, I'll reach out to the Gallery Admins to request the rename!

**Comment by scrthq** [comment]
Request submitted @ScriptAutomate , I'll keep you updated!

**Comment by scrthq** [comment]
hey @ScriptAutomate - all is fixed up on the Gallery side! Let me know how it's working for you. Tested in WSL on my host (Ubuntu 18.04 as well) and it's looking good to me:

![image](https://user-images.githubusercontent.com/12724445/63632855-52a19200-c604-11e9-94c2-acb66d9557f6.png)
