### ISSUE TITLE
how to use parameters

### ISSUE THREAD

**Issue by trondhindenes** [scrthq/Vaporshell#9]
After reading the documentation, it's unclear to me how to reference parameters (corresponding to "ref:" in cloudformation). Could you add some more documentation?

**Comment by scrthq** [comment]
Hey Trond -- Absolutely, I appreciate the feedback! Not sure how deep you dove through the website, but the Module Digest page goes a bit more into Intrinsic Functions like Ref (and includes an example using `Add-FnRef` as well!). Below are some handy links, examples, and details around how I approached writing this module.

***

Useful pages on Intrinsic Functions and overall usage (i.e. remember to surround functions in parentheses when using it directly as a parameter value for another function):

Module Digest: http://vaporshell.io/docs/digest#intrinsic-functions

Function Glossary for Intrinsic Functions: http://vaporshell.io/docs/glossary/#intrinsic-functions

Tips & Tricks: http://vaporshell.io/docs/tips

***

### Example  
You can store functions in a variable then add the variable to another function's parameter as the value (top section - useful if you might be placing that same function elsewhere in your config) or call the function directly as a parameter (See the `KeyName' parameter on `New-VSEC2Instance` below). For `Add-FnRef`, the `Ref` parameter is positional so you can save some typing by just including the ref value right after, as done below as well:

```powershell
$template = Initialize-Vaporshell

<# Add InstanceSecurityGroup, RegionMap and KeyName here #>

$RegRef = Add-FnRef $_AWSRegion
$ImgId = Add-FnFindInMap -MapName "RegionMap" -TopLevelKey $RegRef -SecondLevelKey "AMI"
$SecGrps = Add-FnRef "InstanceSecurityGroup"

$Ec2Ins = New-VSEC2Instance -LogicalId "MyInstance" `
                            -SecurityGroups $SecGrps `
                            -ImageId $ImgId `
                            -KeyName (Add-FnRef "KeyName")

$template.AddResource($Ec2Ins)
```

***

When building this module, I wanted to make function names as predictable as possible given the amount of options to include in CloudFormation templates. I grouped Vaporshell functions as close to AWS documentation's grouping of them, i.e. Intrinsic Functions, Resource Types, Property Types, Resource Attributes, etc. I also tried to follow naming conventions when building each "group" of functions within Vaporshell:  
- Intrinsic functions
    - Add-**Fn**_functionName_, i.e. `Add-FnRef`, `Add-FnGetAtt`, `Add-FnGetAZs`
    - `Ref` is a unique case since it's listed as an intrinsic function, but AWS did not name it `Fn::Ref`
- Condition functions
    - Add-**Con**_functionName_, i.e. `Add-ConAnd`, `Add-ConEquals`
- Resource types
    - **New-VS**_typeName_, i.e. `New-VSEC2Instance`, `New-VSAutoScalingAutoScalingGroup`
- Resource properties
    - **Add-VS**_propertyName_, i.e. `Add-VSApiGatewayApiKeyStageKey`, `Add-VSAutoScalingAutoScalingGroupTagProperty`
- Serverless Application Model
    - Same as Resource / Property Types, except these use "SAM" instead of "VS" in the function name
    - `New-SAMApi`, `New-SAMFunction`, `New-SAMSimpleTable`
    - 'Add-SAMApiEventSource`, `Add-SAMS3LocationObject`

- Vaporshell core functions
    - All have "Vapor" or "Vaporshell" in the name. These typically involve working with the template object, i.e. `Initialize-Vaporshell`, `New-VaporResource`, etc.

***

Hopefully this helps! I've worked most of this into the docs on the website I believe, but any and all feedback/criticism/etc is appreciated!!

Let me know if this answers your question and if you have any suggestions my way for improving the documentation!

**Comment by trondhindenes** [comment]
Ah, that makes sense. Just didn't look in the right place. The template I looked at takes a parameter but doesnt use it, that's probably what threw me off.

**Comment by scrthq** [comment]
No worries! Seems odd for someone to add in a parameter to their template that doesn't get referenced elsewhere, but to each their own ¯\_(ツ)_/¯
